apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-son-frequency-layer-manager.name" . }}-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "eric-son-frequency-layer-manager.name" . }}
    app.kubernetes.io/version: {{ include "eric-son-frequency-layer-manager.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "eric-son-frequency-layer-manager.chart" . }}
    {{- include "eric-son-frequency-layer-manager.user-labels" . | indent 4 }}
  annotations:
  {{- include "eric-son-frequency-layer-manager.product-info" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name:  {{ template "eric-son-frequency-layer-manager.name" . }}-sa
roleRef:
  kind: Role
  name: {{ template "eric-son-frequency-layer-manager.name" . }}-role
  apiGroup: "rbac.authorization.k8s.io"
